# ***NumPy***
NumPy is the fundamental package for scientific computing with Python. It contains among other things:

a powerful N-dimensional array object
sophisticated (broadcasting) functions
tools for integrating C/C++ and Fortran code
useful linear algebra, Fourier transform, and random number capabilities
Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

Library documentation: http://www.numpy.org/**bold text**

In [103]:
from numpy import *

In [104]:
# declare a vector using a list as the argument
v = array([1,2,3,4])
v

array([1, 2, 3, 4])

In [105]:
# declare a matrix using a nested list as the argument
M = array([[1,2],[3,4]])
M

array([[1, 2],
       [3, 4]])

In [106]:
# still the same core type with different shapes
type(v), type(M)

(numpy.ndarray, numpy.ndarray)

In [107]:
M.size

4

In [108]:
# arguments: start, stop, step
x = arange(0, 10, 1)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
linspace(0, 10, 25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [110]:
logspace(0, 10, 10, base=e)


array([1.00000000e+00, 3.03773178e+00, 9.22781435e+00, 2.80316249e+01,
       8.51525577e+01, 2.58670631e+02, 7.85771994e+02, 2.38696456e+03,
       7.25095809e+03, 2.20264658e+04])

In [111]:
x, y = mgrid[0:5, 0:5]
x

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [112]:
y


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [113]:
from numpy import random
random.rand(5,5)

array([[0.7707888 , 0.9285745 , 0.59657912, 0.34000348, 0.65929616],
       [0.95828509, 0.87475521, 0.84016808, 0.73247747, 0.55433797],
       [0.54773604, 0.03954864, 0.62680254, 0.52934499, 0.21711139],
       [0.6227394 , 0.32236755, 0.27468533, 0.9103463 , 0.14394684],
       [0.5879747 , 0.6458471 , 0.09036663, 0.75280973, 0.90136165]])

In [114]:
# normal distribution
random.randn(5,5)

array([[ 0.51471818,  0.67732934,  1.03211497, -0.86207751,  0.16640944],
       [-1.18194886, -1.01479202, -1.8726313 , -0.36792017, -0.45323548],
       [ 0.21649456, -1.74340777,  0.58885597, -0.93764   ,  0.81178823],
       [-0.42019496,  0.24798233, -1.72737253,  0.15312317,  0.15496902],
       [ 1.31259745, -0.36840184,  0.31755829, -0.25289135,  1.36396856]])

In [115]:
diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [116]:
M.itemsize


8

In [117]:
M.nbytes

32

In [118]:
M.ndim

2

In [119]:
v[0], M[1,1]


(1, 4)

In [120]:
M[1]

array([3, 4])

In [121]:
# assign new value
M[0,0] = 7
M

array([[7, 2],
       [3, 4]])

In [122]:
M[0,:] = 0
M


array([[0, 0],
       [3, 4]])

In [123]:
# slicing works just like with lists
A = array([1,2,3,4,5])
A[1:3]

array([2, 3])

In [124]:
A = array([[n+m*10 for n in range(5)] for m in range(5)])
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [125]:
row_indices = [1, 2, 3]
A[row_indices]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [126]:
# index masking
B = array([n for n in range(5)])
row_mask = array([True, False, True, False, False])
B[row_mask]

array([0, 2])

Linear Algebra

In [127]:
v1 = arange(0, 5)
v1 + 2

array([2, 3, 4, 5, 6])

In [128]:
v1 * 2

array([0, 2, 4, 6, 8])

In [129]:
v1 * v1

array([ 0,  1,  4,  9, 16])

In [130]:
dot(v1, v1)

30

In [131]:
dot(A, v1)


array([ 30, 130, 230, 330, 430])

In [132]:
# cast changes behavior of + - * etc. to use matrix algebra
M = matrix(A)
M * M

matrix([[ 300,  310,  320,  330,  340],
        [1300, 1360, 1420, 1480, 1540],
        [2300, 2410, 2520, 2630, 2740],
        [3300, 3460, 3620, 3780, 3940],
        [4300, 4510, 4720, 4930, 5140]])

In [133]:
# inner product
v.T * v


array([ 1,  4,  9, 16])

In [134]:
C = matrix([[1j, 2j], [3j, 4j]])
C

matrix([[0.+1.j, 0.+2.j],
        [0.+3.j, 0.+4.j]])

In [135]:
conjugate(C)

matrix([[0.-1.j, 0.-2.j],
        [0.-3.j, 0.-4.j]])

In [136]:
# inverse
C.I

matrix([[0.+2.j , 0.-1.j ],
        [0.-1.5j, 0.+0.5j]])

Statistics

In [137]:
mean(A[:,3])

23.0

In [138]:
std(A[:,3]), var(A[:,3])

(14.142135623730951, 200.0)

In [139]:
A[:,3].min(), A[:,3].max()

(3, 43)

In [140]:
d = arange(1, 10)
sum(d), prod(d)

(45, 362880)

In [141]:
cumsum(d)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [142]:
cumprod(d)

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880])

In [143]:
# sum of diagonal
trace(A)

110

In [144]:
m = random.rand(3, 3)
m

array([[0.25538424, 0.55234024, 0.4662983 ],
       [0.75585751, 0.49705596, 0.0496953 ],
       [0.51734543, 0.50328746, 0.38447696]])

In [145]:
# use axis parameter to specify how function behaves
m.max(), m.max(axis=0)

(0.7558575057004526, array([0.75585751, 0.55234024, 0.4662983 ]))

In [146]:
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [147]:
# reshape without copying underlying data
n, m = A.shape
B = A.reshape((1,n*m))

B

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30,
        31, 32, 33, 34, 40, 41, 42, 43, 44]])

In [148]:
# modify the array
B[0,0:5] = 5
B

array([[ 5,  5,  5,  5,  5, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30,
        31, 32, 33, 34, 40, 41, 42, 43, 44]])

In [149]:
# also changed
A

array([[ 5,  5,  5,  5,  5],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [150]:
# creates a copy
B = A.flatten()
B

array([ 5,  5,  5,  5,  5, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30, 31,
       32, 33, 34, 40, 41, 42, 43, 44])

In [151]:
# can insert a dimension in an array
v = array([1,2,3])
v[:, newaxis], v[:,newaxis].shape, v[newaxis,:].shape

(array([[1],
        [2],
        [3]]),
 (3, 1),
 (1, 3))

In [152]:
repeat(v, 3)


array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [153]:
tile(v, 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [154]:
w = array([5, 6])

In [155]:
concatenate((v, w), axis=0)

array([1, 2, 3, 5, 6])

In [156]:
# deep copy
B = copy(A)